insert into city values(0, 'Washington');
insert into city values(1, 'New York');
insert into city values(2, 'Long Island');
insert into city values(3, 'New Haven');
insert into city values(4, 'Providence');
insert into city values(5, 'Hartford');
insert into city values(6, 'Allentown');
insert into city values(7, 'Hershey');
insert into city values(8, 'Harrisburg');
insert into city values(9, 'York');
insert into city values(10, 'Lancaster');
insert into city values(11, 'Philadelphia');
insert into city values(12, 'Baltimore');


insert into graph_edge values(0, 1, 9, 60);
insert into graph_edge values(1, 2, 9, 10);
insert into graph_edge values(2, 5, 9, 30);
insert into graph_edge values(3, 2, 1, 15);
insert into graph_edge values(4, 5, 2, 30);
insert into graph_edge values(5, 1, 4, 10);
insert into graph_edge values(6, 4, 5, 10);
insert into graph_edge values(7, 0, 1, 20);
insert into graph_edge values(8, 1, 7, 30);
insert into graph_edge values(9, 5, 6, 40);
insert into graph_edge values(10, 6, 7, 10);
insert into graph_edge values(11, 0, 3, 30);
insert into graph_edge values(12, 3, 7, 10);
insert into graph_edge values(13, 7, 8, 30);
insert into graph_edge values(14, 3, 8, 40);